# Branch Protection Policy Configuration
# This file documents the branch protection rules that should be applied to the main branch
# These settings must be configured through GitHub's repository settings UI or API
# Reference: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches

branch_protection_rules:
  main:
    # Require pull request reviews before merging
    required_pull_request_reviews:
      enabled: true
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
      require_last_push_approval: false
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []
    
    # Require status checks to pass before merging
    required_status_checks:
      strict: true  # Require branches to be up to date before merging
      contexts:
        - "build-and-test (16.x)"
        - "build-and-test (18.x)"
        - "build-and-test (20.x)"
        - "security-scan"
    
    # Require signed commits
    required_signatures: true
    
    # Enforce all configured restrictions for administrators
    enforce_admins: true
    
    # Restrict who can push to matching branches
    restrictions:
      users: []  # Empty means all users with write access are restricted
      teams: []
      apps: []
    
    # Require linear history (no merge commits)
    required_linear_history: false
    
    # Allow force pushes
    allow_force_pushes: false
    
    # Allow deletions
    allow_deletions: false
    
    # Require conversation resolution before merging
    required_conversation_resolution: true
    
    # Lock branch (read-only)
    lock_branch: false
    
    # Allow fork syncing
    allow_fork_syncing: true

# Additional security best practices
security_practices:
  - Keep dependencies up to date using Dependabot
  - Run security scans on all pull requests
  - Require all commits to be signed with GPG/SSH keys
  - Review and approve all changes by code owners
  - Ensure CI/CD checks pass before merging
  - Maintain audit trail of all changes to protected branches
